[tool.isort]
profile = "black"

[tool.black]
line-length = 120
target-version = ['py312']
skip-string-normalization = false

[tool.pytest.ini_options]
pythonpath = ["."]
addopts = "--tb=short -q"
testpaths = ["tests"]
